[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
ammonia = "3.2.0"
askama = "0.11.1"
async-trait = "0.1.56"
axum = { version = "0.5.9", features = ["headers", "http2"] }
color-eyre = "0.6.1"
config = { version = "0.13.1", default-features = false, features = ["toml"] }
eyre = "0.6.8"
sendgrid = { version = "0.17.4", default-features = false, features = ["async", "rustls"] }
serde = "1.0.137"
serde_json = "1.0.81"
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "macros", "migrate", "uuid", "time", "json", "tls", "offline", "postgres"] }
tokio = { version = "1.19.2", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
tracing = "0.1.35"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] } # uuid version kept in sync with sqlx

