[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
axum = { version = "0.5.5", features = ["headers", "http2"] }
color-eyre = "0.6.1"
config = { version = "0.13.1", default-features = false, features = ["toml"] }
eyre = "0.6.8"
serde = "1.0.137"
serde_json = "1.0.81"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "macros", "migrate", "uuid", "time", "json", "tls", "offline", "postgres"] }
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
uuid = { version = "1.0.0", features = ["serde", "v4"] } # uuid version kept in sync with sqlx

