[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
axum = { version = "0.5.4", features = ["headers", "http2"] }
color-eyre = "0.6.1"
config = { version = "0.13.1", features = ["toml"] }
eyre = "0.6.8"
serde = "1.0.137"
serde_json = "1.0.80"
tokio = { version = "1.18.0", features = ["full"] }
tower = "0.4.12"
