[package]
name = "game-night"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
axum = { version = "0.5.5", features = ["headers", "http2"] }
color-eyre = "0.6.1"
config = { version = "0.13.1", features = ["toml"] }
eyre = "0.6.8"
serde = "1.0.137"
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] } 
