name: "Nix Flake"

on:
  pull_request:
    paths:
      - .github/workflows/nix_ci.yml
      - flake.*
      - backend/**
      - frontend/**
  push:
    branches:
      - 'main'
    paths:
      - flake.*
      - backend/**
      - frontend/**

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: game-night
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#game-night-backend
    - run: nix build .#game-night-frontend
    - run: nix build .#game-night-docker
