name: "Nix Flake"

on:
  pull_request:
    paths:
      - .github/workflows/nix_ci.yml
      - flake.*
      - backend/**
      - frontend/**
  push:
    branches:
      - 'main'
    paths:
      - flake.*
      - backend/**
      - frontend/**

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: game-night
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Build Backend
      run: nix build .#game-night-backend

    - name: Build Frontend
      run: nix build .#game-night-frontend

    - name: Build Docker Image
      run: nix build .#game-night-docker

    - name: Log in to the Container Registry
      # TODO - Uncomment before merge
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.DO_TOKEN }}
        password: ${{ secrets.DO_TOKEN }}

    - name: Push Docker Image
      # TODO - Uncomment before merge
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # TODO - There's an action to extract the tags and label so we don't have to hardcode these
        docker load < result
        docker image ls | grep -i game-night
        docker tag game-night:0.1.0 ${{ secrets.REGISTRY }}/game-night-registry/game-night:0.1.0

        docker image ls | grep -i game-night
        docker push ${{ secrets.REGISTRY }}/game-night-registry/game-night:0.1.0

        docker image ls | grep -i game-night
        docker tag game-night:0.1.0 ${{ secrets.REGISTRY }}/game-night-registry/game-night:latest
        docker push ${{ secrets.REGISTRY }}/game-night-registry/game-night:latest


    - name: Deploy App
      # Reference: https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      # TODO - Uncomment before merge
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Setup SSH
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/automation.key
        chmod 600 ~/.ssh/automation.key
        cat >>~/.ssh/config <<END
        Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/automation.key
          StrictHostKeyChecking no
        END

        ssh prod 'whoami'
        ssh prod 'ls -la'
        ssh prod 'pwd'
      env:
          SSH_USER: ${{ secrets.AUTOMATION_USERNAME }}
          SSH_KEY: ${{ secrets.AUTOMATION_SSH_KEY_PRIVATE }}
          SSH_HOST: ${{ secrets.PROD_HOSTNAME }}



