name: "NixOS"

on:
  pull_request:
    paths:
      - .github/workflows/nixos.yml
      - infra/nixos/*
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/nixos.yml
      - infra/nixos/*
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: [Terraform]
    types: [completed]
    branches: [main]

jobs:
  deploy-config:
    name: Deploy Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # TODO
    #  - If not a workflow_run:
    #    - Git diff from last commit to see what files changed if any
    #    - Compare timestamp between remote and local files
    #
    #  - SCP new files to /tmp/nixos
    #  - mv files to /etc/nixos
    #  - run nix-rebuild switch

    - name: Deploy Nixos Configuration
      # Reference: https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      # TODO: Remove comment before merge
      # if: github.ref == 'refs/heads/main'
      run: |
        # Setup SSH
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/automation.key
        chmod 600 ~/.ssh/automation.key
        cat >>~/.ssh/config <<END
        Host prod
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/automation.key
          StrictHostKeyChecking no
        END

        ssh prod "
          set -x
          mkdir -p /tmp/nixos
        "

        scp ./infra/nixos/* prod:/tmp/nixos/

        ssh prod "
          set -x
          ls -la /tmp/nixos
          ls -la /etc/nixos
        "

      env:
        SSH_USER: ${{ secrets.AUTOMATION_USERNAME }}
        SSH_USER_PASSWORD: ${{ secrets.AUTOMATION_USER_PASSWORD }}
        SSH_KEY: ${{ secrets.AUTOMATION_SSH_KEY_PRIVATE }}
        SSH_HOST: ${{ secrets.PROD_HOSTNAME }}




